### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by H3wastooshort** [ff3l/site-ff3l#82]
getting:

`lede/staging_dir/hostpkg/bin/lua: scripts/site_config.lua:10: scripts/site_config.lua:6: attempt to index a nil value
stack traceback:
[C]: ?
[C]: in function 'load'
scripts/site_config.lua:10: in main chunk
[C]: ?
stack traceback:
[C]: in function 'assert'
scripts/site_config.lua:10: in main chunk
[C]: ?
Your site configuration (site.conf) did not pass validation.
Makefile:148: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 1`

**Comment by kpanic23** [comment]
It seems you are building Gluon master.
The master branch of the site is only compatible with Gluon 2017.1.x.
For Gluon master you need to use the "next" branch.
I have now moved the "next" branch to master, and the changes in the former master branch to 2017.1 branch.
Please pull the master branch again, then you should be able to build Gluon master.

**Comment by H3wastooshort** [comment]
im usng tha master brancr of ff3l-site

**Comment by H3wastooshort** [comment]
ashit waht s my keyboard typing

**Comment by kpanic23** [comment]
I have done some fixes to master branch, please run "git pull" in /site directory
